= My Solution

== Overview

This chapter details my solution to the problem.
The traditional software engineering task-based organization is used.
Section 1 describes the requirements of the solution, focusing on features.
Section 2 describes the architecture of the solution.
Section 3 describes the implementation of the solution.
Hardware and software topics are covered in section 3, from physical
installation to the graphical user interface.
Section 4 describes the testing regime undertaken during the development of
this project.

== Requirements

This project's goal is to produce a software platform that is capable of
powering a reference hardware platform based on retail components providing
audio, some mobile phone integration, and navigation functionality to an
automobile.

=== Features

==== Graphical Display

The project should display its system state via a Graphical User Interface.

==== 4-channel Audio Support

The project should be able to output digital audio in four independent channels,
all configurable by the operating system.

==== Audio Playback Support

The project should be able to decode for playback the most common formats of
multimedia documents, especially MP3, MP2, m4a (Unprotected MPEG-4 AAC audio),
and FLAC (Free Lossless Audio). The project should also include the capacity to
add decode support for new formats in the future, as long as the underlying
hardware can decode the information in real time.

==== Arbitrary Execution

The device should be capable of executing any properly built and installed
programs desired by the user. The user will only need a software development
kit (SDK) including a compiler for the specific device's architecture and the
development resources such as libraries and headers.

==== Remote Administration

The project should be capable of remote administration on any desired, capable
network interface. No physical manipulation of the target device should be
required in order to change most internal settings and perform over-the-air
software updates.

==== Personal Media Device Support

The project should interface with personal media devices available to the
underlying operating system. The solution presented in this project will support
USB-connected devices which provide a USB Mass Storage device and a readable
filesystem to the host system.

=== Bluetooth Integration

The project should support wireless networking over the Bluetooth protocol. This
protocol will allow users to link the device with mobile phones in order to
provide call and messaging notification.

=== GPS Navigation

The project should support geolocation if a GPS device is installed.

== Metrics

=== Monetary Cost

This project relies entirely upon free software. The hardware reference
platform's bill of materials is the only monetary cost associated with the
project. The intent of this project is to undercut the cost of existing
solutions that are available to retail customers.

=== Boot Time

The time for a device to start up from a powered-off state will be measured and
compared to other comparable systems such as mobile phones and personal
computers. The goal is to achieve a quick boot time that is acceptable to
automotive end-users and effort will be taken to minimize this value.

=== Filesystem Size

While storage is inexpensive, this project doesn't intend to store a large
amount of data. Furthermore, it intends to include as little as possible code to
maximize performance and maintainability. Efforts will be made to minimize the
filesystem size and occupy much less storage space than existing mobile
operating systems.

include::hardware.adoc[]

== Software Architecture

=== Platform

The project was designed with simplicity, performance, and modularity in mind.
Its target hardware is cheap single-board computers.  These motivations
influenced the choice of a development platform.

=== Organization

The project is designed into several service components, each with a
well-defined role and programming interface. This type of organization allows
for independent development of components, a clear separation of concerns, and
autonomous behavior of each component. If the tools are also given their own
process space in a modern multi-process operating system such as Linux, there is
also the potential for increased security and robustness against failures in one
component. In fact, the application code of this project was designed as a set
of interfaces for the D-Bus interprocess messaging system <<dbus>>.

include::implementation.adoc[]
